### ISSUE TITLE
gradle dependency not working. Have you missed to add custom repository?

### ISSUE THREAD

**Issue by metalurgus** [armcha/SimplePermissions#1]
`compile 'com.github.armcha:SimplePermissions:1.0.0'` is not enough to import/use project. 

> Error:(32, 13) Failed to resolve: com.github.armcha:SimplePermissions:1.0.0

Are you sure you didn't miss some custom repository like 
```
repositories {
    maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
}
```

**Comment by armcha** [comment]
@metalurgus For me it works fine, try to add this custom repository 
`repositories {
    maven {
        url 'https://dl.bintray.com/armcha/maven'
    }
}`

**Comment by metalurgus** [comment]
ok, this solved a problem. Could you edit README.MD and add this pre-requirement to the Download/How to use since it is not obvious?

**Comment by armcha** [comment]
@metalurgus sure
